### ISSUE TITLE
Can't use an undefined value as a HASH reference

### ISSUE THREAD

**Issue by Zwork101** [Caaz/panda-saver#1]
Hey, after running this program for a day, the next day after, it started displaying this whenever I went to start playing songs.

```
Can't use an undefined value as a HASH reference at panda.pl line 91.
```

Now I tried to understand what was happening, but it's a little confusing due to the fact I'm not very familiar with perl.

```perl
my $waitTime = 0;
      for my $track (@{$result->{'items'}}) {
        my ($file,$offset) = save($track);
        $waitTime += get_mp3info($file)->{SECS}-$offset if(defined $file && defined $offset);
      }
waitFor($waitTime, 'Simulating playhead %s');
```

**Comment by Caaz** [comment]
Windows specific shenanigans. Windows Media Player locking access to files. Not much I know how to get around this besides running the program as sudo (probably not the best plan) or otherwise giving access to the files to the program.
